config/routes.rb
# http://stackoverflow.com/questions/4207657/rails-routing-to-handle-multiple-domains-on-single-application
class FormatConstraint
  def initialize
  end
 
  def matches?(request)
    request.user_agent =~ /Mobile|webOS/ && (request.user_agent =~ /ipad/i).nil? ? true : false
  end
end

Creamcheese::Application.routes.draw do
  if Rails.env.production?
    # http://stackoverflow.com/questions/4372896/rails-ensuring-www-is-in-the-url
    redirect_proc = Proc.new { 
      redirect do |params, request|
        URI.parse(request.url).tap { |x| x.host = "www.philadelphia.com.mx" }.to_s
      end
    }
    constraints(host: "philadelphia.com.mx") do
      match "(*x)" => redirect_proc.call
    end
    constraints(host: "creamcheese.herokuapp.com") do
      match "(*x)" => redirect_proc.call
    end
  end
  
  match 'academia' => redirect('http://www.academiaphiladelphia.com.mx/cocina-elaborada')
  match 'consentidas' => redirect('http://www.consentidas.com.mx/')
  
  
  

  constraints FormatConstraint.new do
    root :to => 'mobile#index'
    get 'index' => "mobile#index"
    get 'premios' => "mobile#premios"
    get 'recetas' => 'mobile#index'
    get 'recetas/buscar' => "mobile#buscar"
    get 'recetas/:categoria' => "mobile#recetas", as: 'mobile_recetas'
    get 'recetas/recetaslista' => "mobile#recetaslista", as: 'recetaslista'
    get 'catmobile' => "mobile#catmobile", as: 'catmobile'
    
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'index#index'

  get 'festejemos' => 'index#festejemos'
  get 'reto' => 'index#reto'
  get 'recomendada' => 'index#recomendada'

  resources :pages
   match 'chatyaz' => 'pages#chatyaz'
   match 'premios' => 'pages#premios'
   match 'promobases'  => 'pages#promobases'
   
   
  get 'boletin' => 'chimp#index'
  post 'boletin' => 'chimp#suscripcion'

  match 'salud/imc' => 'salud#imc'
  match 'salud/calorias' => 'salud#calorias'
  match 'salud/peso' => 'salud#peso'

  match 'recetas' => 'receta#index'
  match 'recetas/index' => redirect('/recetas')
  match 'recetas/service'  => 'receta#service'
  match 'producto' => redirect('/#producto')
  match 'noticias' => redirect('/')
  match 'index.php' => redirect('/')
  match 'receta/:id(/:slug.html)' => 'receta#show', as: 'receta', constraints: { id: /\d{1,3}/ }
  match 'receta/busqueda' => 'receta#busqueda'
  match 'receta/busquedaapp' => 'receta#busquedaapp'
  match 'recetas(/:tipo)/busqueda' => 'receta#busqueda'
  match 'recetas/feed' => 'receta#feed'
  match 'recetas/comunidad' => 'receta#comunidad'
  match 'recetas(/:categoria)' => redirect('/recetas')
  # match 'receta_mail/:id' => 'receta#mail', as: 'receta_mail'

  match 'marca/politicas' => 'marca#politicas'
  match 'marca/ayuda' => 'marca#ayuda'
  match 'marca/legal' => 'marca#legal'
  match 'marca/contacto' => 'marca#contacto'
  match 'marca/promocion' => 'marca#promocion'
  
  match "chat" => 'chat#index'
  get "chat/call"

  match 'recompensas' => redirect('http://recompensasphiladelphia.com')

  # redirecciona la direccion que aparece en un QR a un video
  match 'yazmin' => redirect('/recetas')
  match 'qr/:qr' => 'index#qr'

  #ultima ruta siempre plx
  match '*a' => 'errors#routing'
end

app/views/base/_analytics.html.haml
:javascript
  window._gaq = [['_setAccount','#{ENV['ANALYTICS_KEY']}'],['_trackPageview'],['_trackPageLoadTime'],
    ['k._setAccount', '#{ENV['ANALYTICS_KEY2']}'],['k._trackPageview']];
  Modernizr.load({
    load: ('https:' == location.protocol ? '//ssl' : '//www') + '.google-analytics.com/ga.js'
  })

app/views/base/_footer.html.haml
%footer.block
  .col_40
    %a.logo_footer{:href => "/#marca"}
    %br
    .mas
      .styled
        %select
          %option Más de la familia kraft
          %option{:value => "//www.kraft-philadelphia.at"} Philadelphia Austria
          %option{:value => "//www.philadelphia.co.uk"} Philadelphia Inglaterra
          %option{:value => "//www.philadelphia.com.br"} Philadelphia Brasil
          %option{:value => "//www.philadelphia.de"} Philadelphia Alemania
          %option{:value => "//www.philadelphia.info"} Philadelphia en el Mundo
          %option{:value => "//www.hemelsevariaties.nl"} Philadelphia Holanda

     
  .col_60
    %ul#menu_footer
      %li= link_to 'Contáctenos', marca_contacto_path
      %li= link_to 'Preguntas frecuentes', marca_ayuda_path
      %li= link_to 'Política de privacidad y términos de uso', marca_politicas_path
      %li= link_to 'Aviso Legal', marca_legal_path

app/views/base/_menu.html.erb
<script type="text/javascript">
function notifywhat(){
 $('#notifywhat').fadeIn('200');
}
function hidewhat(){
$('#notifywhat').fadeOut('200');

}
</script>
<link href="http://fonts.googleapis.com/css?family=Bree+Serif" rel="stylesheet" type="text/css">
<header class="block">
			<div class="col_header_1">
				<div id="btnsuscribe"><a href="/#nosotrasyphiladelphia"></a></div>
			</div>
			<div class="col_header_2">
				<div id="logoheader">
				<a class="logolink" href="/#home"></a>
				</div>
			</div>
			<div class="col_header_3" id="social_btns">
			<p class="title_soc">Sé parte de las redes Philadelphia®</p>
				<ul>
					<li><a class="soc_facebook" target="_blank" href="http://www.facebook.com/philadelphiamx"></a></li>
					<li><a class="soc_twitter" target="_blank" href="http://twitter.com/philadelphiamx"></a></li>
					<li><a class="soc_youtube" target="_blank" href="http://www.youtube.com/user/philadelphiamexico"></a></li>
          <li><a class="soc_pinterest" target="_blank" href="https://pinterest.com/philadelphiamx/"></a></li>
					<li><a class="soc_telefono" target="_blank" title="WhatsApp" onclick="notifywhat();"></a></li>
					<div id="notifywhat" style="display:none; width:250px; height:120px; margin-left:-45px; z-index:1000; position:absolute;"><img src="http://philadelphia.com.mx/yazwhatsappmsg-bg.png" onclick="hidewhat();"/></div>
					<li><a class="soc_instagram" target="_blank" href="http://instagram.com/philadelphiamx/"></a></li>
				</ul>
				
			</div>
			
<div class="inside">

<nav>
<a class="producto" href="/#marca">Marca</a>
<a class="recetas" href="/recetas">Recetas</a>
<a class="nosotrasyphiladelphia" href="/#nosotrasyphiladelphia">Nosotras y Philadelphia®</a>
<a class="foodservice" href="/#foodservice">Food Service</a>


<a class="basicos" href="/#basicos">Básicos de cocina</a>
<!-- <a class="recompensas" href="http://www.consentidas.com.mx/" target="_blank">consentidas</a> -->
</nav>

</div>
</header>

app/views/base/_menu.html.haml
%header
  %nav
    %a.producto{:href => "/#marca"} Marca
    =link_to 'Recetas', recetas_path, { class: "recetas #{@recetas_nuevas ? 'new' : nil} #{@recetas_activo ? 'active' : nil}"}
    %a.twolines.nosotrasyphiladelphia{:href => "/#nosotrasyphiladelphia"} Nosotras y Philadelphia
    %a.twolines.foodservice{:href => "/#foodservice"} Food Service
    %h1#logo{:style => "position: absolute; top: -34px; left: 50%; margin-left: -94px;"}
      %a{:href => "/#home"} Philadelphia México
    %a.twolines.preguntaleayaz{style: 'margin-left: 200px', :href => "/#preguntaleayaz"} Pregúntale a Yaz
    %a.twolines.basicos{:href => "/#basicos"} Básicos de cocina
    /%a.recompensas{:href => "http://recompensasphiladelphia.com/" } 
  %menu.secundario
    %ul
      %li.inlineblock{ style: "position: relative; top: 10px;"}
        Sé parte de las redes Philadelphia®
      %li
        %a.inlineblock.twitter{:target => "_blank", :href => "//twitter.com/philadelphiamx"}
          %span twitter
      %li
        %a.inlineblock.facebook{:target => "_blank", :href => "//www.facebook.com/philadelphiamx"}
          %span Facebook
      %li
        %a.inlineblock.youtube{:target => "_blank", :href => "//youtube.com/philadelphiamexico"}
          %span Youtube
      -#%li
      -#  %a.inlineblock.blogger{:target => "_blank", :href => "//blogspot.com/"}
      -#    %span Blogspot
      -#%li
      -#  %a.inlineblock.gplus{:target => "_blank", :href => "//plus.google.com/100360379304245749280"}
      -#    %span Google+
  %menu.extra
    %ul
      %li.boletin
        %a.inlineblock.bg-icon{ :href => "/#nosotrasyphiladelphia" }
          %span
            Boletín