config/routes.rb
# http://stackoverflow.com/questions/4207657/rails-routing-to-handle-multiple-domains-on-single-application
class FormatConstraint
  def initialize
  end
 
  def matches?(request)
    request.user_agent =~ /Mobile|webOS/ && (request.user_agent =~ /ipad/i).nil? ? true : false
  end
end

Creamcheese::Application.routes.draw do
  if Rails.env.production?
    # http://stackoverflow.com/questions/4372896/rails-ensuring-www-is-in-the-url
    redirect_proc = Proc.new { 
      redirect do |params, request|
        URI.parse(request.url).tap { |x| x.host = "www.philadelphia.com.mx" }.to_s
      end
    }
    constraints(host: "philadelphia.com.mx") do
      match "(*x)" => redirect_proc.call
    end
    constraints(host: "creamcheese.herokuapp.com") do
      match "(*x)" => redirect_proc.call
    end
  end
  
  match 'academia' => redirect('http://www.academiaphiladelphia.com.mx/cocina-elaborada')
  match 'consentidas' => redirect('http://www.consentidas.com.mx/')
  
  
  

  constraints FormatConstraint.new do
    root :to => 'mobile#index'
    get 'index' => "mobile#index"
    get 'premios' => "mobile#premios"
    get 'recetas' => 'mobile#index'
    get 'recetas/buscar' => "mobile#buscar"
    get 'recetas/:categoria' => "mobile#recetas", as: 'mobile_recetas'
    get 'recetas/recetaslista' => "mobile#recetaslista", as: 'recetaslista'
    get 'catmobile' => "mobile#catmobile", as: 'catmobile'
    
  end

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root to: 'index#index'

  get 'festejemos' => 'index#festejemos'
  get 'reto' => 'index#reto'
  get 'recomendada' => 'index#recomendada'

  resources :pages
   match 'chatyaz' => 'pages#chatyaz'
   match 'premios' => 'pages#premios'
   match 'promobases'  => 'pages#promobases'
   
   
  get 'boletin' => 'chimp#index'
  post 'boletin' => 'chimp#suscripcion'

  match 'salud/imc' => 'salud#imc'
  match 'salud/calorias' => 'salud#calorias'
  match 'salud/peso' => 'salud#peso'

  match 'recetas' => 'receta#index'
  match 'recetas/index' => redirect('/recetas')
  match 'recetas/service'  => 'receta#service'
  match 'producto' => redirect('/#producto')
  match 'noticias' => redirect('/')
  match 'index.php' => redirect('/')
  match 'receta/:id(/:slug.html)' => 'receta#show', as: 'receta', constraints: { id: /\d{1,3}/ }
  match 'receta/busqueda' => 'receta#busqueda'
  match 'receta/busquedaapp' => 'receta#busquedaapp'
  match 'recetas(/:tipo)/busqueda' => 'receta#busqueda'
  match 'recetas/feed' => 'receta#feed'
  match 'recetas/comunidad' => 'receta#comunidad'
  match 'recetas(/:categoria)' => redirect('/recetas')
  # match 'receta_mail/:id' => 'receta#mail', as: 'receta_mail'

  match 'marca/politicas' => 'marca#politicas'
  match 'marca/ayuda' => 'marca#ayuda'
  match 'marca/legal' => 'marca#legal'
  match 'marca/contacto' => 'marca#contacto'
  match 'marca/promocion' => 'marca#promocion'
  
  match "chat" => 'chat#index'
  get "chat/call"

  match 'recompensas' => redirect('http://recompensasphiladelphia.com')

  # redirecciona la direccion que aparece en un QR a un video
  match 'yazmin' => redirect('/recetas')
  match 'qr/:qr' => 'index#qr'

  #ultima ruta siempre plx
  match '*a' => 'errors#routing'
end

app/controllers/mobile_controller.rb
class MobileController < ApplicationController
  def index
  end

  def buscar
    r = Recipe.busqueda(params[:busqueda][:q]).order("recetas.tiempo, recetas.id").page(params[:page]).per(24)
    @recetas = r.publicado
    render :recetas
  end

  def recetas
    r = Recipe.order("recetas.orden, recetas.tiempo, recetas.id").page(params[:page]).per(24)

    f = []
    case params[:categoria]
      when 'sopas'
        f << 'p_sopa'
      when 'platos_fuertes'
        f << 'p_carne'
        f << 'p_cerdo'
        f << 'p_aves'
        f << 'p_pescado'
      when 'postres'
        f << 'p_postre'
      when 'botanas'
        f << 'p_botana'
      when 'pasta'
        f << 'p_pasta'
    end
    
    @recetas = r.porplatillo(f).publicado
  end
  
 	
 	
 	
 	def recetaslista
    r = Recipe.order("recetas.orden, recetas.tiempo, recetas.id").page(params[:page]).per(24)

    f = []
    case params[:categoria]
      when 'sopas'
        f << 'p_sopa'
      when 'platos_fuertes'
        f << 'p_carne'
        f << 'p_cerdo'
        f << 'p_aves'
        f << 'p_pescado'
      when 'postres'
        f << 'p_postre'
      when 'botanas'
        f << 'p_botana'
      when 'pasta'
        f << 'p_pasta'
    end
    
    @recetas = r.porplatillo(f).publicado
  end


  def catmobile
  
  end
  
end

app/views/mobile/catmobile.mobile.erb
<div class="block">
<div class="container_categoria_recetas">
<%= link_to(image_tag('mobile/botanas_btn.png', class: 'menu-icon', size: '93x89'), mobile_recetas_path(:botanas)) %>
    <%= link_to(image_tag('mobile/sopas_btn.png', class: 'menu-icon', size: '93x89'), mobile_recetas_path(:sopas)) %>
    <%= link_to(image_tag('mobile/pastas_btn.png', class: 'menu-icon', size: '93x89'), mobile_recetas_path(:pasta)) %>
    <%= link_to(image_tag('mobile/fuertes_btn.png', class: 'menu-icon', size: '93x89'), mobile_recetas_path(:platos_fuertes)) %>
    <%= link_to(image_tag('mobile/postres_btn.png', class: 'menu-icon', size: '93x89'), mobile_recetas_path(:postres)) %>
</div>
</div>

app/views/mobile/desafiountable.html.erb
</style>
<div style="margin-left:auto; margin-right:auto;width:100%">
   <div style="width:816px; height:1001px; margin:0 auto;">
      <iframe src="http://apps.circusmarketing.com/academia_untables/iframe" height="900" width="815" frameborder="0" style="margin-left: auto; margin-right: auto;">
   </iframe>
  </div>
</div>

app/views/mobile/desafiountable.mobile.erb
<style>
body {
  background: #d3d3d3 url('Philadelphia-site-home-BG.jpg');
  overflow-y: scroll;
  font-family: $frutiger;
}
</style>
<div style="margin-left:auto; margin-right:auto;width:100%">
   <div style="width:816px; height:1001px; margin:0 auto;">
      <iframe src="http://apps.circusmarketing.com/academia_untables/iframe" height="900" width="815" frameborder="0" style="margin-left: auto; margin-right: auto;">
   </iframe>
  </div>
</div>

app/views/mobile/index.mobile.erb
<div id="wrapper_mobile320">

		
<div id="main_mobile320">

<a class="preparar_hoy320" href="/catmobile"></a>
<a class="academia_320" href="http://www.academiaphiladelphia.com.mx/"></a>
<a class="consentidas_320" href="http://www.consentidas.com.mx"></a>

</div>
		



</div>	

app/views/mobile/pre_index.mobile.erb
<style>
 .block{display:none;}
</style>
<div id="preindex_mobile320" style="display:block">
   <a href="/index"><div id="index_link"></div></a>
</div>

app/views/mobile/premios.mobile.erb
<style type="text/css">
body{background: #E2E2E3}
#wrapperpremios{background:#dadada; width: 779px; margin:0 auto;}
.rowpremios{width: 779px; float:left; margin:0;}
.divcenter{width: 200px; margin :10px auto;}
</style>


<div id="wrapperpremios">

<div class="rowpremios" style="text-align:center;">
<img src="assets/premios/cuponera_Philadelphia_08012013.jpg" alt="cuponera"  />
</div>




<div class="rowpremios">
<div class="divcenter">
<a href="http://www.bwigo.com/philadelphia/imagenes/cuponera-tema.pdf"><img src="assets/premios/boton-premios.jpg" alt="boton-premios" width="193" height="64" /></a>
</div>

</div>


<div class="rowpremios">
<div class="divcenter">
<img src="assets/premios/saludo-premios.jpg"  />
</div>
</div>





</div>

app/views/mobile/recetas.mobile.haml
%section#opciones-mobile
  .sub-menu
    %a{ :href => '#', :'data-rel' => 'back', :class => 'regresar-icon' } regresar 
    / =image_tag 'mobile/regresar.png', class: 'regresar-icon'
    / %a{ :href => '#', :class => 'vista' } vista 
    / =image_tag 'mobile/regresar.png', class: 'regresar-icon'
    / %a{ :href => '#', :class => 'vista-lista' } lista
    / =image_tag 'mobile/regresar.png', class: 'regresar-icon'
  .mobile-lista
    %ul.mobile-lista
      - @recetas.each do |receta|
        %li
          %a{ :href => receta_path(receta.id, receta.slug) }
            .imagen
              - unless receta.pic_big_file_name.nil?
                = image_tag receta.pic_big.url(:normal)
              - else
                - unless receta.recipe_photo.blank?
                  = image_tag receta.recipe_photo
                - else
                  =image_tag("http://phillybeta.outofthebox.mx/recetas/clasico/#{receta.imagen}.jpg")
            .descripcion
              .titulo
                %h1 
                  = receta.titulo
              .tiempo
                %h2!= "Tiempo de preparación:<b> #{receta.tiempo} minutos.</b>"
              .porciones
                %h2!= "Porciones:<b> #{receta.porciones}</b>"
              .platillos
                %h2
                  =image_tag 'mobile/platillo_icon.png', class: 'platillo-icon'
                  = receta.tipo_platillo
  = paginate @recetas
  / .mobile-view
  /   #slideshow
  /     %ul
  /       %li
  /         %img{:src => "http://placekitten.com/500/300", :width => "500", :height => "300", :alt => ""}
  /       %li
  /         %img{:src => "http://placekitten.com/501/301", :width => "500", :height => "300", :alt => ""}
  /       %li
  /         %img{:src => "http://placekitten.com/502/302", :width => "500", :height => "300", :alt => ""}
  /       %li
  /         %img{:src => "http://placekitten.com/503/303", :width => "500", :height => "300", :alt => ""}
  /       %li
  /         %img{:src => "http://placekitten.com/504/304", :width => "500", :height => "300", :alt => ""}
  /   #overview
  /     %ul>
  /       %li 1
  /       %li 2
  /       %li 3
  /       %li 4
  /       %li 5